apiVersion: v1
kind: Service
metadata:
  name: cicd-app-jenkins-deploy
  labels:
    app: teamcontainer
spec:   
  ports:  
  - name: "http"  
    port: 80  
    targetPort: 8080  
  selector:  
    app: teamcontainer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-jenkins-service
  labels:
    app: teamcontainer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: teamcontainer
  template:
    metadata:
      labels:
        app: teamcontainer
    spec:
      containers:
      - name: teamcontainer
        image: 674583976178.dkr.ecr.us-east-2.amazonaws.com/teamimagerepo:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
